/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hikmet_Terzioglu_Part2_project;
import java.util.ArrayList;
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
    public static int findAndAdd(ArrayList<Integer> array,int x,int y){
        if(array==null)
            return -1000;

        if(y<0)
            return -1000;


        for(int i=0;i<array.size();i++){
            if(array.get(i)<0){
                return -1000;
            }

        }    
        boolean contains=false;
        int added=0;
        for(int i=0;i<array.size();i++){
            if(array.get(i)==x){
                contains=true;
                added =array.get(i)+y;
                break;
            } 
         
        }    
        if(contains==false){
            return -1000;

        }else{
            return added;
        }
        
    }
}
