/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hikmet_Terzioglu_Part2_project;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;
import java.util.Arrays;
 
class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void nullTest(){
        int result;
        result=App.findAndAdd(null, 10, 20);
        assertEquals(-1000,result);
        
    }
    @Test void notContain(){
        int result;
        ArrayList<Integer> arr=new ArrayList<Integer>();
        arr.add(10);
        arr.add(20);
        arr.add(30);
        result=App.findAndAdd(arr, 15, 20);
        assertEquals(-1000,result);
        
    }

    @Test void added(){
        int result;
        ArrayList<Integer> arr=new ArrayList<Integer>();
        arr.add(10);
        arr.add(20);
        arr.add(30);
        result=App.findAndAdd(arr, 10, 20);
        assertEquals(30,result);
        

    }
    
    @Test void yNegative(){
        int result;
        ArrayList<Integer> arr=new ArrayList<Integer>();
        arr.add(10);
        arr.add(20);
        arr.add(30);
        result=App.findAndAdd(arr, 10, -20);
        assertEquals(-1000,result);
    
    }
    @Test void containsNegative(){
        int result;
        ArrayList<Integer> arr=new ArrayList<Integer>();
        arr.add(-10);
        arr.add(20);
        arr.add(30);
        result=App.findAndAdd(arr, 10, 20);
        assertEquals(-1000,result);
    
    }



}
